config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/auth/:provider/callback', to: 'sessions#omniauth'
  root to: "application#landing_page"
  resources :users do 
    collection do
    end

    member do
    end
  end

  resources :sessions do 
    collection do 
      post :login
      post :logout
    end

    member do 
    end
  end
  
  resources :books do 
    collection do
      get :available_books
      get :unavailable_books
    end
  end

  resources :welcome

  resources :libraries, only: [:show] do
    collection do
      get :invalid
    end

    member do 
      patch :remove_book_from_library
    end
    
    resources :media_transactions, only: [:new, :create, :index] 
  end



end

app/models/user.rb
class User < ApplicationRecord
  has_one :library
  has_secure_password
  validates :username, presence: true, length: {minimum: 3, maximum: 25}, uniqueness: true
  validates :email, presence: true
  validates_confirmation_of :password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show]

  def index
  end

  def new
    @user = User.new
  end 

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id

      # build was not working here. @user.library was returning nil, so I couldn't run build on it
      Library.create(user_id: @user.id)
      return redirect_to library_path(@user.library)
    else
      render :new
    end
  

  end

  def show
    current_user 
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :public)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% if logged_in? %>

<% else %>

  <h1>Welcome to your media library. Sign up or log in -- then stay awhile.</h1>

  <% form_with scope: :session, url: login_sessions_path %>
<% end %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
      <% @user.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="ml-8 mt-8 w-4/12">

  <h1 class="font-bold text-3xl text-center mb-4">Create your account:</h1>

  <%= form_with model: @user, url: users_path, method: :post do |f| %>
    <%= f.label :email, class: "uppercase font-bold text-lg text-grey-darkest mb-1" %>
    <%= f.text_field :email, class: "w-12/12 pl-2 border border-black rounded" %>
    <br><br>
    <%= f.label :username, class: "uppercase font-bold text-lg text-grey-darkest mb-1" %>
    <%= f.text_field :username, class: "w-12/12 pl-2 border border-black rounded" %>
    <br><br>
    <%= f.label :password, class: "uppercase font-bold text-lg text-grey-darkest mb-1" %>
    <%= f.password_field :password, class: "w-12/12 pl-2 border border-black rounded" %>
    <br><br>
    <%= f.label :password_confirmation, class: "uppercase font-bold text-lg text-grey-darkest mb-1" %>
    <%= f.password_field :password_confirmation, class: "w-12/12 pl-2 border border-black rounded" %>
    <br><br>
    <%= f.submit "Sign up", class: "p-2 bg-indigo-400 text-lg text-white rounded-xl cursor-pointer" %>
  <% end %>
  <br>
  <%= link_to("Already have an account?", sessions_path) %><br><br>
  <%= link_to("Sign In With Google", '/auth/google_oauth2', method: :post) %>
</div>