config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/auth/:provider/callback', to: 'sessions#omniauth'
  root to: "application#landing_page"
  resources :users do 
    collection do
    end

    member do
    end
  end

  resources :sessions do 
    collection do 
      post :login
      post :logout
    end

    member do 
    end
  end
  
  resources :books do 
    collection do
      get :available_books
      get :unavailable_books
    end
  end

  resources :welcome

  resources :libraries, only: [:show] do
    collection do
      get :invalid
    end

    member do 
      patch :remove_book_from_library
    end
    
    resources :media_transactions, only: [:new, :create, :index] 
  end



end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :library, optional: :true
  has_many :book_transactions
  has_many :media_transactions, through: :book_transactions

  validates :title, presence: :true
  validates :author, presence: :true
  validates :description, presence: :true, length: {minimum: 100 }, allow_blank: false

  scope :available, -> { where(library_id: nil) }
  scope :unavailable, -> { where.not(library_id: nil) }
  
  # isbn regex
  # /^(?=(?:\D*\d){10}(?:(?:\D*\d){3})?$)[\d-]+$/

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :current_user
  before_action :current_book, only: [:edit, :update]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(books_params)
    @book.created_by_user_id = @user.id

    if @book.save 
      return redirect_to book_path(@book)
    else
      render "books/new"
    end
  end

  def edit
    if @book.created_by_user_id == @user.id
      render "books/edit"
    else 
      redirect_to invalid_libraries_path
    end
  end

  def show
    @book = Book.find_by_id(params[:id])
    @library = User.find(session[:user_id]).library
  end

  def update
    if @book.created_by_user_id == @user.id && @book.update(books_params)
      redirect_to book_path(@book)
    else
      render 'books/edit'
    end
  end

  def destroy
    book = Book.find_by_id(params[:id])
    book.destroy

    redirect_to books_path
  end

  def available_books
    @books = Book.available
  end

  def unavailable_books
    @books = Book.unavailable
  end

  private 

  def books_params
    params.require(:book).permit(:title, :author, :description, :image_path)
  end

  def current_book
    @book = Book.find_by_id(params[:id])
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def checked_out?(book)
    true if book.library_id != nil
  end
  
  def checkout_class(book)
    if checked_out?(book)
      "mt-6 p-2 bg-red-600 text-lg text-white rounded-xl cursor-not-allowed"
    else
      "mt-6 p-2 bg-indigo-500 text-lg text-white rounded-xl cursor-pointer"
    end
  end

  def disable_checkout_button?(book)
    checked_out?(book)
  end

  def checkout_button_text(book)
    checked_out?(book) ? "Not Available" : "Checkout Book"
  end

  def reserved_until(book)
    book.book_transactions.last.reservation_end_date.strftime("%m-%d-%Y")
  end

  def days_until_reservation_ends

  end

  def availability(book)
    if book.library_id != User.find(session[:user_id]).library.id && book.library_id != nil && !book.book_transactions.empty?
      "Available on #{reserved_until(book)}"
    elsif book.library_id == User.find(session[:user_id]).library.id
      "This book is in your library"
    else
      "Available"
    end
  end

  def availability_class(book)
    if availability(book) == "Available"
      "w-6/12 mb-3 mx-auto text-center font-bold bg-green-500 text-white text-sm rounded-xl"
    elsif availability(book) == "This book is in your library"
      "w-8/12 mb-3 mx-auto text-center font-bold bg-blue-500 text-white text-sm rounded-xl"
    else
      "w-8/12 mb-3 mx-auto text-center font-bold bg-red-500 text-white text-sm rounded-xl"
    end
  end

end

app/views/books/_book_form.html.erb
<% if book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(book.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
      <% book.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="ml-8 mt-8 w-4/12">
  <h1 class="font-bold text-3xl text-center mb-4">Add a new book:</h1>
  <%= form_with model: book do |f| %>

  <div class="flex flex-col mb-4">
    <%= f.label :title, class: "uppercase font-bold text-lg text-grey-darkest mb-1" %>
    <%= f.text_field :title, class: "w-12/12 pl-2 border border-black rounded" %>
  </div>
  <div class="flex flex-col mb-4">
    <%= f.label :author, class: "uppercase font-bold text-lg text-grey-darkest mb-1" %>
    <%= f.text_field :author, class: "w-8/12 pl-2 border border-black rounded" %>
  </div>
  <div class="flex flex-col mb-4">
    <%= f.label :description, class: "uppercase font-bold text-lg text-grey-darkest mb-1" %>
    <%= f.text_area :description, class: "w-12/12 pl-2 border border-black rounded text-xs h-24" %>
  </div>
  <div class="flex flex-col mb-4">
    <%= f.label :image_path, class: "uppercase font-bold text-lg text-grey-darkest mb-1" %>
    <%= f.text_field :image_path, class: "w-12/12 pl-2 border border-black rounded" %>
  </div>
    <%= f.submit class: "p-2 bg-indigo-400 text-lg text-white rounded-xl cursor-pointer" %>
  <% end %>
</div>

app/views/books/edit.html.erb
<%= render partial: "book_form", :locals => {:book => @book} %>

app/views/books/index.html.erb
<h1 class="text-center text-4xl font-bold">Browse Books:</h1>

<div class="flex justify-center space-x-12 mt-4">
  <%= link_to("Available Books", available_books_books_path) %>
  <%= link_to("Unavailable Books", unavailable_books_books_path) %>
</div>

<div class="w-10/12 mx-auto my-4 overflow-auto flex flex-wrap">
<% @books.order(:name).each do |book| %>
  <div class="bg-gray-100 w-3/12 h-auto mx-12 my-8 border-black border-2 rounded-xl text-center" >
    <h2 class="text-blue-700 my-4 text-center text-3xl italic"><%= link_to "#{book.title}", book_path(book) %></h1>
    <p class="<%= availability_class(book) %>"><%= availability(book) %></p>
    <h3 class="mb-4 text-center font-bold"><%= book.author %></h3>
    <img class="mx-auto mb-3" src="<%= book.image_path %>" width="125" height="200">
    <% if book.created_by_user_id == @user.id %>
      <%= link_to("Edit Book", edit_book_path(book), class: "mx-auto text-center mb-6") %>
    <% end %>
    <% if book.created_by_user_id == @user.id %>
      <%= link_to("Delete Book", book_path(book), :method => :delete) %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/books/new.html.erb
<%= render partial: "book_form", :locals => {:book => @book} %>
  

app/views/books/show.html.erb
<div class="w-full h-full flex justify-center">
  <div class="w-8/12 flex flex-col">
    <h1 class="text-center italic text-4xl my-6"><%= @book.title %></h1>
    <h3 class="text-center font-bold text-2xl mb-6"><%= @book.author %></h3>
    <p class="whitespace-pre-wrap text-xl mx-10 mb-6"><%= @book.description %></p>
    <img class="mx-auto" src="<%= @book.image_path %>" width="225" height="300">
    <div class="flex justify-center">
      <%= form_with model: @book, url: new_library_media_transaction_path(library_id: @library.id), method: :get do |f| %>
        <%= f.hidden_field(:id) %>
        <%= f.submit checkout_button_text(@book), class: "#{checkout_class(@book)}", disabled: checked_out?(@book) %>
      <% end %>
    </div>
  
  </div>
</div>

app/views/books/unavailable_books.html.erb
<h1 class="text-center text-4xl font-bold">Browse All Unavailable Books:</h1>


<div class="w-10/12 mx-auto my-4 overflow-auto flex flex-wrap">
<% @books.order(:name).each do |book| %>
  <div class="bg-gray-100 w-3/12 h-auto mx-12 my-8 border-black border-2 rounded-xl text-center" >
    <h2 class="text-blue-700 my-4 text-center text-3xl italic"><%= link_to "#{book.title}", book_path(book) %></h1>
    <p class="<%= availability_class(book) %>"><%= availability(book) %></p>
    <h3 class="mb-4 text-center font-bold"><%= book.author %></h3>
    <img class="mx-auto mb-3" src="<%= book.image_path %>" width="125" height="200">
    <% if book.created_by_user_id == @user.id %>
      <%= link_to("Edit Book", edit_book_path(book), class: "mx-auto text-center mb-6") %>
    <% end %>
  </div>
  <% end %>
</div>