config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/auth/:provider/callback', to: 'sessions#omniauth'
  root to: "application#landing_page"
  resources :users do 
    collection do
    end

    member do
    end
  end

  resources :sessions do 
    collection do 
      post :login
      post :logout
    end

    member do 
    end
  end
  
  resources :books do 
    collection do
      get :available_books
      get :unavailable_books
    end
  end

  resources :welcome

  resources :libraries, only: [:show] do
    collection do
      get :invalid
    end

    member do 
      patch :remove_book_from_library
    end
    
    resources :media_transactions, only: [:new, :create, :index] 
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def landing_page
    if session.include?(:user_id)
      @user = User.find_by_id(session[:user_id].to_s)
      redirect_to library_path(@user.library)
    else
      render "application/landing_page"
    end
  end

  private

  def current_user
    @user = User.find_by_id(session[:user_id].to_s)
  end

  def logged_in?
    session.include?(:user_id)
  end

  def require_login
    redirect_to login_path, alert: "You must be logged in to view this page." unless logged_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @user = User.find_by(id: session[:user_id])
  end

  def logged_in?
    session.include?(:user_id)
  end
end

app/views/application/landing_page.html.erb
<div class="w-screen h-screen place-content-center flex place-content-center items-center">
  <div class="w-6/12 my-18 h-24">
    <h1 class="text-center">Welcome to your media library. Sign up or log in -- then stay awhile.</h1>
    <div class="flex space-x-5 mt-8 justify-center">
      <%= button_to("Sign up", new_user_path, method: :get) %>
      <%= button_to("Log in", sessions_path, method: :get) %>
    </div>
  </div>
</div>


