config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/auth/:provider/callback', to: 'sessions#omniauth'
  root to: "application#landing_page"
  resources :users do 
    collection do
    end

    member do
    end
  end

  resources :sessions do 
    collection do 
      post :login
      post :logout
    end

    member do 
    end
  end
  
  resources :books do 
    collection do
      get :available_books
      get :unavailable_books
    end
  end

  resources :welcome

  resources :libraries, only: [:show] do
    collection do
      get :invalid
    end

    member do 
      patch :remove_book_from_library
    end
    
    resources :media_transactions, only: [:new, :create, :index] 
  end



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLibraryAppMod3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 
      <% if session[:user_id] %>
        <div class="w-screen h-12 bg-blue-200 flex justify-center">
          <div class="mx-8">
            <%= link_to("All Books", books_path) %>
          </div>
          <div class="mx-8">
            <%= link_to("New Book", new_book_path) %>
          </div>
          <div class="mx-8">
            <%= link_to("My Library", library_path(current_user.library)) %>
          </div>
          <div clas="mx-8">
            <%= link_to("My Transactions", library_media_transactions_path(current_user.library)) %>
          </div>
          <div class="mx-8">
            <%= link_to("Logout", '/sessions/logout', method: :post) %>
          </div>
        </div>
      <% end %>

    <%= yield %>
  </body>
</html>